<a href="https://colab.research.google.com/github/sdtasneem/AIDS-Projects/blob/main/PaySentinel_%E2%80%93_Payment_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.Data Loading**

In [174]:
import pandas as pd

In [175]:
# Load the dataset
df=pd.read_csv('Datasets.csv')

In [176]:
df

,Unnamed: 0,step,type,branch,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,unusuallogin,isFlaggedFraud,Acct type,Date of transaction,Time of day,isFraud
0,0,1,PAYMENT,Indonesia,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,9,0,Current,3/1/2018,Morning,0.0
1,1,1,PAYMENT,India,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,10,0,Savings,5/1/2018,Morning,0.0
2,2,1,TRANSFER,India,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,2,0,Current,7/1/2018,Morning,1.0
3,3,1,CASH_OUT,Australia,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0,Current,6/1/2018,Afternoon,1.0
4,4,1,PAYMENT,Australia,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,17,0,Current,6/1/2018,Morning,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,10122,7,PAYMENT,Cuba,337.50,C1494306005,33107.0,32769.50,M1424027000,0.0,0.0,7,0,Current,3/1/2018,Afternoon,0.0
10123,10123,7,PAYMENT,Mexico,5003.57,C1633890169,32769.5,27765.93,M1854745805,0.0,0.0,11,0,Savings,5/1/2018,Morning,0.0
10124,10124,7,PAYMENT,Panama,10424.89,C1026138669,50780.0,40355.11,M1852900317,0.0,0.0,6,0,Savings,7/1/2018,Night,0.0
10125,10125,7,PAYMENT,Mexico,2823.59,C378659213,986.0,0.00,M301812950,0.0,0.0,12,0,Savings,6/1/2018,Night,0.0
10126,10126,7,PAYMENT,Cuba,8126.71,C1639296014,6423.0,0.00,M129774606,0.0,0.0,11,0,Current,2/1/2018,Afternoon,0.0

**2.Data Cleaning**

In [177]:
# renaming the column name
df.rename(columns={'Unnamed: 0': 'transaction_id'}, inplace=True)

In [178]:
#displaying all columns
df.columns

Index(['transaction_id', 'step', 'type', 'branch', 'amount', 'nameOrig',
       'oldbalanceOrg', 'newbalanceOrig', 'nameDest', 'oldbalanceDest',
       'newbalanceDest', 'unusuallogin', 'isFlaggedFraud', 'Acct type',
       'Date of transaction', 'Time of day', 'isFraud'],
      dtype='object')

In [179]:
# displaying Number of rows and columns
df.shape

(10127, 17)

In [180]:
# Check for missing values
df.isnull().sum()

transaction_id          0
step                    0
type                    4
branch                  0
amount                  2
nameOrig                6
oldbalanceOrg           2
newbalanceOrig          0
nameDest                6
oldbalanceDest          1
newbalanceDest          2
unusuallogin            0
isFlaggedFraud          0
Acct type              10
Date of transaction     7
Time of day             2
isFraud                 2
dtype: int64

In [181]:
# checking for duplicates
df.duplicated().sum()

np.int64(0)

In [182]:
# dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   transaction_id       10127 non-null  int64
 1   step                 10127 non-null  int64
 2   type                 10123 non-null  object
 3   branch               10127 non-null  object
 4   amount               10125 non-null  float64
 5   nameOrig             10121 non-null  object
 6   oldbalanceOrg        10125 non-null  float64
 7   newbalanceOrig       10127 non-null  float64
 8   nameDest             10121 non-null  object
 9   oldbalanceDest       10126 non-null  float64
 10  newbalanceDest       10125 non-null  float64
 11  unusuallogin         10127 non-null  int64
 12  isFlaggedFraud       10127 non-null  int64
 13  Acct type            10117 non-null  object
 14  Date of transaction  10120 non-null  object
 15  Time of day          10125 non-null  object
 16  isFraud              10125 non-null  float64
dtypes: float64(6), int64(4), object(7)
memory usage: 1.3+ MB

In [183]:
# column datatypes
df.dtypes

transaction_id           int64
step                     int64
type                    object
branch                  object
amount                 float64
nameOrig                object
oldbalanceOrg          float64
newbalanceOrig         float64
nameDest                object
oldbalanceDest         float64
newbalanceDest         float64
unusuallogin             int64
isFlaggedFraud           int64
Acct type               object
Date of transaction     object
Time of day             object
isFraud                float64
dtype: object

In [184]:
# removing null values from isfraud column
df = df.dropna(subset=['isFraud'])

In [185]:
# filling the missing values with median
num_cols = [
    'amount',
    'oldbalanceOrg',
    'newbalanceOrig',
    'oldbalanceDest',
    'newbalanceDest'
]

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

/tmp/ipykernel_2983/743013702.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].fillna(df[col].median())

In [186]:
# filling the missing values with mode
cat_cols = [
    'type',
    'branch',
    'Acct type',
    'Time of day'
]

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

/tmp/ipykernel_2983/3466164565.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].fillna(df[col].mode()[0])

In [187]:
# changing the datatype of isfraud column
df['isFraud'] = df['isFraud'].astype(int)

/tmp/ipykernel_2983/2808278011.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['isFraud'] = df['isFraud'].astype(int)

In [189]:
# Check the value counts and percentage distribution of the isFraud column
print(df['isFraud'].value_counts())
print(f" In Percentage :{(df['isFraud'].value_counts(normalize=True))*100}")

isFraud
0    10057
1       68
Name: count, dtype: int64
 In Percentage :isFraud
0    99.328395
1     0.671605
Name: proportion, dtype: float64

**3. Feature Preparation**

In [190]:
# Separate features and target variable
features = [
    'step',
    'type',
    'branch',
    'amount',
    'oldbalanceOrg',
    'newbalanceOrig',
    'oldbalanceDest',
    'newbalanceDest',
    'unusuallogin',
    'isFlaggedFraud',
    'Acct type',
    'Time of day'
]
x=df[features]
y=df['isFraud']

In [193]:
# Split the dataset into training and testing sets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42, stratify=y)

In [194]:
# checking the shape of x_train and x_test
print("Training:", x_train.shape)
print("Testing :", x_test.shape)

Training: (8100, 12)
Testing : (2025, 12)

In [195]:
# checking the shape of y_train and y_test
print("training value count:\n",y_train.value_counts())
print("testing value count:\n",y_test.value_counts())

training value count:
 isFraud
0    8046
1      54
Name: count, dtype: int64
testing value count:
 isFraud
0    2011
1      14
Name: count, dtype: int64

In [196]:
categorical_cols = [
    'type',
    'branch',
    'Acct type',
    'Time of day'
]
X_train_encoded = x_train.copy()
X_test_encoded = x_test.copy()

**4.Encoding**

In [197]:
# Encode categorical features into numerical values
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder(
    handle_unknown='use_encoded_value',
    unknown_value=-1
)

X_train_encoded[categorical_cols] = encoder.fit_transform(
    x_train[categorical_cols]
)

X_test_encoded[categorical_cols] = encoder.transform(
    x_test[categorical_cols]
)

print(X_train_encoded.head())

      step  type  branch    amount  oldbalanceOrg  newbalanceOrig  \
1043     1   3.0     7.0  10932.41            0.0            0.00
3393     2   1.0    35.0  32969.34       164131.0       131161.66
9077     7   3.0    51.0   7663.31            0.0            0.00
9953     7   3.0    44.0   6863.99            0.0            0.00
4101     3   3.0    54.0  26084.81        40746.0        14661.19

      oldbalanceDest  newbalanceDest  unusuallogin  isFlaggedFraud  Acct type  \
1043             0.0            0.00            12               0        0.0
3393         48615.1        81584.44            15               0        1.0
9077             0.0            0.00             6               0        1.0
9953             0.0            0.00             3               0        1.0
4101             0.0            0.00            10               0        1.0

      Time of day
1043          1.0
3393          0.0
9077          1.0
9953          0.0
4101          2.0

**5.Handling Class Imbalance**

In [198]:
# Handle class imbalance using SMOTENC

from imblearn.over_sampling import SMOTENC

categorical_indices = [
    X_train_encoded.columns.get_loc(col)
    for col in categorical_cols
]

smotenc = SMOTENC(
    categorical_features=categorical_indices,
    random_state=42
)

x_train_resampled, y_train_resampled = smotenc.fit_resample(
    X_train_encoded,
    y_train
)

print("Before SMOTENC:")
print(y_train.value_counts())

print("\nAfter SMOTENC:")
print(y_train_resampled.value_counts())

Before SMOTENC:
isFraud
0    8046
1      54
Name: count, dtype: int64

After SMOTENC:
isFraud
0    8046
1    8046
Name: count, dtype: int64

**6. Model Training**

In [199]:
# Train the Random Forest fraud detection model
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight='balanced',
    n_jobs=-1
)

model.fit(x_train_resampled, y_train_resampled)

print("Model training completed!")

Model training completed!

In [200]:
X_test_encoded.head()

,step,type,branch,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,unusuallogin,isFlaggedFraud,Acct type,Time of day
4678,4,4.0,35.0,1137763.15,0.00,0.00,5500286.37,6671931.33,8,0,1.0,2.0
5993,6,3.0,55.0,11506.17,206846.00,195339.83,0.00,0.00,8,0,0.0,2.0
5427,5,3.0,40.0,1324.06,0.00,0.00,0.00,0.00,12,0,0.0,0.0
3789,3,3.0,97.0,4402.18,190942.49,186540.30,0.00,0.00,18,0,0.0,0.0
1651,1,3.0,97.0,3677.29,0.00,0.00,0.00,0.00,15,0,0.0,0.0

**7. Model Evaluation**

In [201]:
# Evaluate model performance
y_pred = model.predict(X_test_encoded)
y_prob = model.predict_proba(X_test_encoded)[:, 1]

In [202]:
from sklearn.metrics import *
print("Classification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2011
           1       0.71      0.86      0.77        14

    accuracy                           1.00      2025
   macro avg       0.85      0.93      0.89      2025
weighted avg       1.00      1.00      1.00      2025

In [203]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[2006    5]
 [   2   12]]

In [204]:
print("ROC-AUC:", roc_auc_score(y_test, y_prob))
print("PR-AUC:", average_precision_score(y_test, y_prob))

ROC-AUC: 0.9982773318178588
PR-AUC: 0.7640127729413444

In [205]:
# Convert fraud probability into a 0-100 risk score
risk_score = (y_prob * 100).round(2)

print(risk_score[:10])

[ 0.5  0.   0.   0.   0.   0.   0.  81.5  0.   0. ]

**8.Risk Scoring & Decision Engine**

In [206]:
# Assign risk level
def get_risk_level(score):
    if score < 30:
        return "LOW"
    elif score < 70:
        return "MEDIUM"
    else:
        return "HIGH"

In [207]:
# assign transaction decision
def get_decision(score):
    if score < 30:
        return "APPROVE"
    elif score < 70:
        return "REVIEW"
    else:
        return "BLOCK"

In [208]:
risk_level = [get_risk_level(score) for score in risk_score]
decision = [get_decision(score) for score in risk_score]

In [209]:
results = x_test.copy()
results['Actual_Fraud'] = y_test.values
results['Fraud_Probability'] = y_prob
results['Risk_Score'] = risk_score
results['Risk_Level'] = risk_level
results['Decision'] = decision

In [210]:
results.head(10)

,step,type,branch,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,unusuallogin,isFlaggedFraud,Acct type,Time of day,Actual_Fraud,Fraud_Probability,Risk_Score,Risk_Level,Decision
4678,4,TRANSFER,El Salvador,1137763.15,0.00,0.00,5500286.37,6671931.33,8,0,Savings,Night,0,0.005,0.5,LOW,APPROVE
5993,6,PAYMENT,Indonesia,11506.17,206846.00,195339.83,0.00,0.00,8,0,Current,Night,0,0.000,0.0,LOW,APPROVE
5427,5,PAYMENT,Estados Unidos,1324.06,0.00,0.00,0.00,0.00,12,0,Current,Afternoon,0,0.000,0.0,LOW,APPROVE
3789,3,PAYMENT,Reino Unido,4402.18,190942.49,186540.30,0.00,0.00,18,0,Current,Afternoon,0,0.000,0.0,LOW,APPROVE
1651,1,PAYMENT,Reino Unido,3677.29,0.00,0.00,0.00,0.00,15,0,Current,Afternoon,0,0.000,0.0,LOW,APPROVE
1289,1,CASH_IN,El Salvador,57262.72,4374599.01,4431861.74,72917.77,16896.70,17,0,Current,Night,0,0.000,0.0,LOW,APPROVE
5115,5,PAYMENT,Irlanda,2205.72,16725.71,14519.98,0.00,0.00,15,0,Current,Afternoon,0,0.000,0.0,LOW,APPROVE
7002,6,TRANSFER,Estados Unidos,10224.00,10224.00,0.00,0.00,0.00,15,0,Savings,Night,1,0.815,81.5,HIGH,BLOCK
2790,2,CASH_IN,Italia,208366.03,8271112.67,8479478.70,2980462.29,2798692.37,17,0,Savings,Afternoon,0,0.000,0.0,LOW,APPROVE
7487,7,PAYMENT,China,3439.96,10030.60,6590.64,0.00,0.00,5,0,Savings,Afternoon,0,0.000,0.0,LOW,APPROVE

In [211]:
print(results['Risk_Level'].value_counts())

Risk_Level
LOW       1996
MEDIUM      21
HIGH         8
Name: count, dtype: int64

In [212]:
print(results['Decision'].value_counts())

Decision
APPROVE    1996
REVIEW       21
BLOCK         8
Name: count, dtype: int64

In [213]:
feature_info = {
    "features": features,
    "categorical_cols": categorical_cols
}

**9.Model Saving**

In [214]:
# Save the trained model and preprocessing information
import pickle

with open("paysentinel_model.pkl", "wb") as f:
    pickle.dump(model, f)

with open("paysentinel_encoder.pkl", "wb") as f:
    pickle.dump(encoder, f)

with open("paysentinel_feature_info.pkl", "wb") as f:
    pickle.dump(feature_info, f)

print("All files saved successfully!")

All files saved successfully!

**10. Streamlit Deployment**

In [251]:
%%writefile app.py

import streamlit as st
import pandas as pd
import pickle

# Load saved files
with open("paysentinel_model.pkl", "rb") as f:
    model = pickle.load(f)

with open("paysentinel_encoder.pkl", "rb") as f:
    encoder = pickle.load(f)

with open("paysentinel_feature_info.pkl", "rb") as f:
    feature_info = pickle.load(f)

features = feature_info["features"]
categorical_cols = feature_info["categorical_cols"]

st.set_page_config(
    page_title="PaySentinel",
    page_icon="🛡️",
    layout="wide"
)

st.title("🛡️ PaySentinel")
st.subheader("AI-Powered Payment Risk Intelligence")

st.divider()

st.header("Transaction Details")

col1, col2 = st.columns(2)

with col1:
    step = st.number_input(
        "Step",
        min_value=0,
        value=1
    )

    transaction_type = st.selectbox(
        "Transaction Type",
        ["PAYMENT", "TRANSFER", "CASH_OUT", "DEBIT", "CASH_IN"]
    )

    branch = st.selectbox(
        "Branch",
        ["India", "Japan", "Australia", "Mexico", "Cuba", "Panama"]
    )

    amount = st.number_input(
        "Transaction Amount",
        min_value=0.0,
        value=1000.0
    )

    oldbalanceOrg = st.number_input(
        "Old Origin Balance",
        min_value=0.0,
        value=5000.0
    )

    newbalanceOrig = st.number_input(
        "New Origin Balance",
        min_value=0.0,
        value=4000.0
    )

with col2:
    oldbalanceDest = st.number_input(
        "Old Destination Balance",
        min_value=0.0,
        value=1000.0
    )

    newbalanceDest = st.number_input(
        "New Destination Balance",
        min_value=0.0,
        value=2000.0
    )

    unusual_login = st.selectbox(
        "Unusual Login",
        [0, 1]
    )

    flagged_fraud = st.selectbox(
        "Flagged Fraud",
        [0, 1]
    )

    acct_type = st.selectbox(
        "Account Type",
        ["Savings"]
    )

    time_of_day = st.selectbox(
        "Time of Day",
        ["Morning", "Afternoon", "Evening", "Night"]
    )

st.divider()

if st.button("🔍 Analyze Transaction", use_container_width=True):

    input_data = pd.DataFrame([{
        "step": step,
        "type": transaction_type,
        "branch": branch,
        "amount": amount,
        "oldbalanceOrg": oldbalanceOrg,
        "newbalanceOrig": newbalanceOrig,
        "oldbalanceDest": oldbalanceDest,
        "newbalanceDest": newbalanceDest,
        "unusuallogin": unusual_login,
        "isFlaggedFraud": flagged_fraud,
        "Acct type": acct_type,
        "Time of day": time_of_day
    }])

    input_data = input_data[features]

    input_data[categorical_cols] = encoder.transform(
        input_data[categorical_cols]
    )

    prediction = model.predict_proba(input_data)[0]

    probability = prediction[1]

    risk_score = round(probability * 100, 2)

    if risk_score < 30:
        risk_level = "LOW"
        decision = "APPROVE"

    elif risk_score < 70:
        risk_level = "MEDIUM"
        decision = "REVIEW"

    else:
        risk_level = "HIGH"
        decision = "BLOCK"

    st.divider()

    st.header("Risk Analysis")

    c1, c2, c3 = st.columns(3)

    with c1:
        st.metric(
            "Risk Score",
            f"{risk_score}/100"
        )

    with c2:
        st.metric(
            "Risk Level",
            risk_level
        )

    with c3:
        st.metric(
            "Decision",
            decision
        )

    if decision == "APPROVE":
        st.success(" Transaction Approved")

    elif decision == "REVIEW":
        st.warning("Transaction Requires Manual Review")

    else:
        st.error(" Transaction Blocked")

    st.info(
        f"Fraud probability predicted by the model: {probability:.2%}"
    )

Overwriting app.py

In [252]:
!pip install -q streamlit pyngrok

In [253]:
import subprocess
import time

process = subprocess.Popen(
    ["streamlit", "run", "app.py", "--server.port", "8501"]
)

time.sleep(5)

print("PaySentinel Streamlit app started!")

PaySentinel Streamlit app started!

In [255]:
# PaySentinel Public URL: Run the cell below to generate the temporary public URL for the Streamlit application.
from pyngrok import ngrok

ngrok.kill()

public_url = ngrok.connect(8501)

print(public_url)

NgrokTunnel: "https://twilight-frigidity-nervous.ngrok-free.dev" -> "http://localhost:8501"

In [256]:
# Click the above link to open the PaySentinel Streamlit application